### ISSUE TITLE
git lfs pull error

### ISSUE THREAD

**Issue by wangjunren2735** [BUAA-BDA/OpenHuFu#128]
when I run git lfs pull command,then has an error like this
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/BUAA-BDA/OpenHuFu.git/info/lfs'

**Comment by KoSpades** [comment]
Also got this error.

**Comment by SongY123** [comment]
The reason is that the GitHub LFS storage quota has been exceeded.
