### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by KoSpades** [BUAA-BDA/OpenHuFu#132]
When running the command: bash scripts/build/package.sh, I got the following error: 

Unable to resolve artifact: Missing:
[ERROR] ----------
[ERROR] 1) com.google.protobuf:protoc:exe:osx-aarch_64:3.12.0

In the previous step, I have gotten the error "This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access".

What is causing this, and how can I fix it?

**Comment by SongY123** [comment]
Previously, we discovered that there were issues when running package.sh for our project on computers with Apple Silicon chips. Based on your feedback, we have now found that the same problem occurs on MacOS systems, even with x64 chips. You can refer to the instructions in the ReadME and resolve the running issue for package.sh by specifying os.detected.classifier in Maven settings.xml. As for the issue with Git LFS, our account currently uses the free allowance on GitHub, which will be reset in a few days. Alternatively, you can download the corresponding files directly from the TPC-H website.

**Comment by KoSpades** [comment]
Hi,

I actually managed to solve this issue with by specifying "mvn clean install -T ${thread} -Dmaven.test.skip=true -DskipTests -Dos.detected.classifier=osx-x86_64" in package.sh.

However, now I got a different error in compiling openhufu-aby, the error is as follows:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project openhufu-aby: Compilation failure: Compilation failure: 
[ERROR] /Users/kos/OtherProjects/OpenHuFu/aby4j/src/main/java/com/hufudb/openhufu/mpc/aby/party/Aby4jParty.java:[14,9] cannot find symbol
[ERROR]   symbol:   class Party
[ERROR]   location: class com.hufudb.openhufu.mpc.aby.party.Aby4jParty
[ERROR] /Users/kos/OtherProjects/OpenHuFu/aby4j/src/main/java/com/hufudb/openhufu/mpc/aby/party/Aby4jParty.java:[31,41] cannot find symbol
[ERROR]   symbol:   class e_role
[ERROR]   location: class com.hufudb.openhufu.mpc.aby.party.Aby4jParty
[ERROR] /Users/kos/OtherProjects/OpenHuFu/aby4j/src/main/java/com/hufudb/openhufu/mpc/aby/party/Aby4jParty.java:[43,69] cannot find symbol
[ERROR]   symbol:   class e_role

Any idea how to fix?

**Comment by SongY123** [comment]
The aby module is currently under development. As aby does not currently support macOS systems, we plan to remove it from the current repository and integrate it into the project as a plugin in the future. The separation work is currently in progress, and you can temporarily disable this module in the POM file to solve compilation problems.

**Comment by KoSpades** [comment]
Thanks! I got around this by checking out a previous commit actually.
