### ISSUE TITLE
How do I just get the benchmarks up and running?

### ISSUE THREAD

**Issue by KoSpades** [BUAA-BDA/OpenHuFu#136]
So far I have got to the step of building the project.

I don't have the git-lfs stuff (skipped that step).

I just want to get the codebase up and running. So I ran "bash scripts/test/benchmark.sh", and got the following problem:

java.nio.file.NoSuchFileException: file:/OpenHuFu/benchmark/target/benchmarks.jar!/endpoints.json

I saw that there exists some sample data under dataset/sample/tpc-h, and I would be fine using that dataset. Is there a more complete, step-to-step guide I can follow, just to see things in action? I am specifically trying to run benchmark/test/OpenHufuBenchmarkTest.

If you think it's easier to resolve these issues over emails, feel free to send me an email at stevenxia@uchicago.edu, so we do not have to take up space here 👍 

Thanks!

**Comment by SongY123** [comment]
We have added some instructions for benchmarks in the README. You can fetch the latest code once the PR is merged.

**Comment by KoSpades** [comment]
resolved
