### ISSUE TITLE
how can i use mysql to run a demo?

### ISSUE THREAD

**Issue by serein-dream** [BUAA-BDA/OpenHuFu#169]
As title, I need to run a demo (hufu-spatial branch) (knn query / distance query / max / min and so on) by mysql, but I didn't see the example by MySQL in readme.
Could you please provide some instructions to guide me in importing data into MySQL and compiling the corresponding. jar package to run "./start_driver.sh 1 2 3 4 and./start_cli. sh"
Thanks!

**Comment by SongY123** [comment]
You can adapt MySQL by modifying the configuration files under the "hufu-demo-osm/driver/" folder. There is an example for PostgreSQL in these configuration files, and the meaning of this configuration file is quite understandable. What you need to keep in mind is that MySQL's spatial coordinate field is "POINT."

**Comment by serein-dream** [comment]
Thank you very much for your answer!  I have successfully imported the MySQL database and run   './start_driver.sh 1 2 3 4' and './start_cli. sh'   successfully.
But when I ran     "Hu Fu>SELECT id From osm_a WHERE KNN (Point (121.5, 14.5), location, 8);"    , I meet an error:    "Error: Error while executing SQL" SELECT id From osm_a WHERE KNN (Point (60.75, 7.25), location, 8) ": From line 1, column 52 to line 1, column 59: Column 'location' not found in any table (state=, code=0)
I conducted some tests: running    'select location from osm_a_1;'     in MySQL ,  it  successfully ran and provided 100rows of data.
May I ask where the problem may be?
Thanks again!

**Comment by SongY123** [comment]
The description of cli configuration is in hufu-docs/CLIConfig.md. Before running start_cli.sh, you need to modify model.json as described in the README.

**Comment by serein-dream** [comment]
Thanks for your answer again!  I have run successfully, but meet some error when query by mysql. 
Could you give me a new "mysql_server.jar"  that  replace "Distance" with "ST_Distance" in  "OpenHuFu-hufu-spatial/hufu-mysql-driver/src/main/java/group/bda/federate/driver/utils/MysqlIRTranslator.java".
Because When i run "Federated Range Query / Range Counting / kNN", append. 
So, I test in mysql "SELECT id,**Distance**(location, ST_GeomFromText('POINT(121.5 14.5)')) from osm_a_1 WHERE TRUE ORDER BY  **Distance**(location, ST_GeomFromText('POINT(121.5 14.5)')) ASC  LIMIT 8;"  and "SELECT COUNT(*) from osm_a_2 WHERE Distance(ST_GeomFromText('POINT(60.0 7.0)'), location) <= 10;" ,   I get the error "ERROR 1305 (42000): FUNCTION osm_db.Distance does not exist" .  But i change "Distance" to "ST_Distance"  ("SELECT id,**ST_Distance**(location, ST_GeomFromText('POINT(121.5 14.5)')) from osm_a_1 WHERE TRUE ORDER BY  **ST_Distance**(location, ST_GeomFromText('POINT(121.5 14.5)')) ASC  LIMIT 8;"  and "SELECT COUNT(*) from osm_a_2 WHERE Distance(ST_GeomFromText('POINT(60.0 7.0)'), location) <= 10;") , it works.

**Comment by SongY123** [comment]
Thank you for your feedback. 

  Upon verification, it has been observed that in MySQL version 5.7, spatial fields can utilize the functions Distance() and ST_Distance(). However, starting from MySQL 8.0, the Distance() function has been deprecated. I believe your issue arises in versions MySQL 8.0 and above. Please refer to the following documentation：
https://dev.mysql.com/doc/refman/5.7/en/built-in-function-reference.html, MySQL 5.7:
https://dev.mysql.com/doc/refman/8.0/en/built-in-function-reference.html, MySQL 8.0

  Therefore, you can modify the Distance() function in the file "hufu-mysql-driver/src/main/java/group/bda/federate/driver/utils/MysqlIRTranslator.java" by replacing it with ST_Distance(). After making this change, recompile to generate the mysql_driver.jar file. The issue has already been addressed in the PR https://github.com/BUAA-BDA/OpenHuFu/pull/170, and you can also update your code and recompile accordingly.

**Comment by serein-dream** [comment]
Thank you very much! I have run it successfully
