### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by xiao1du** [BUAA-BDA/OpenHuFu#182]
hello! I am build hu-fu spatial find a problem,./package.sh can not run，because Unable to obtain 'hufu-core/target/*-with-dependencies.jar' ，it can not find

**Comment by SongY123** [comment]
Are you running the hufu-spatial branch? I didn't encounter the issue you mentioned during my compilation.
![IntelliJ IDEA 2024-07-06  17 19 21](https://github.com/BUAA-BDA/OpenHuFu/assets/10370382/9b64a682-c521-44d1-bba8-21b258157d5b)

**Comment by SongY123** [comment]
If you no longer encounter this problem, I will go ahead and close this issue.
